# Generated by Django 4.2.1 on 2023-05-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0002_appoinment_doc_sess_patientlog_register_staffs_vital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('reception', 'Reception'), ('vitals', 'Vitals'), ('laboratory', 'laboratory'), ('pharmacy', 'Pharmacy')], default='user', max_length=10),
        ),
    ]
