# Generated by Django 4.2.1 on 2023-05-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0005_lab_res_delete_lab_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('reciever', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('file', models.FileField(default='no file', upload_to='files/')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
