# Generated by Django 4.2.1 on 2023-05-25 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0007_rename_messages_comm_rename_reciever_comm_receiver'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lab_res',
            new_name='lab',
        ),
        migrations.AlterModelTable(
            name='lab',
            table='lab',
        ),
    ]
