# Generated by Django 4.2.1 on 2023-05-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0008_rename_lab_res_lab_alter_lab_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comm',
            name='id',
        ),
        migrations.AlterField(
            model_name='comm',
            name='sender',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
