# Generated by Django 4.2.1 on 2023-05-25 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0009_remove_comm_id_alter_comm_sender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lab',
            new_name='laboratory',
        ),
    ]
