# Generated by Django 4.2.1 on 2023-05-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0011_communication_lab_data_delete_comm_delete_laboratory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='communication',
            table='messages1',
        ),
        migrations.AlterModelTable(
            name='lab_data',
            table='lab1',
        ),
    ]
