# Generated by Django 4.2.1 on 2023-05-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0013_alter_communication_table_alter_lab_data_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communication',
            old_name='receiver',
            new_name='reciever',
        ),
        migrations.AddField(
            model_name='communication',
            name='subject',
            field=models.CharField(default='no subject', max_length=100),
        ),
        migrations.AlterField(
            model_name='communication',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
