# Generated by Django 4.2.1 on 2023-05-25 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0014_rename_receiver_communication_reciever_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communication',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
