# Generated by Django 4.2.1 on 2023-05-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0015_rename_reciever_communication_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='sender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='communication',
            name='subject',
            field=models.CharField(default='no subject', max_length=100, primary_key=True, serialize=False),
        ),
    ]
