# Generated by Django 4.2.1 on 2023-05-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0018_alter_communication_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='allergies',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='register',
            name='chronic_illness',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='register',
            name='current_meds',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='register',
            name='emg_relationship',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='register',
            name='identification',
            field=models.FileField(default='', max_length=500, upload_to=''),
        ),
        migrations.AddField(
            model_name='register',
            name='past_surgeries',
            field=models.CharField(default='', max_length=200),
        ),
    ]
