# Generated by Django 4.2.1 on 2023-05-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0020_remove_register_current_meds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='messages_files/'),
        ),
        migrations.AlterField(
            model_name='register',
            name='identification',
            field=models.FileField(blank=True, null=True, upload_to='patient_id_files/'),
        ),
    ]
