# Generated by Django 4.2.1 on 2023-05-28 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0022_register_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='profile_photo',
        ),
    ]
