# Generated by Django 4.2.1 on 2023-05-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0024_register_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='profile_photo',
            field=models.FileField(blank=True, upload_to='patient_id_files/'),
        ),
    ]
